# Generate the json inventory for conga and update host file on target systems
- import_playbook: include-prepare-inventory.yml

# compile conga configuration
- import_playbook: include-conga-maven.yml

# When provisioning a single host with multiple CONGA nodes and variants only hostpatterns matching one role are allowed

# Apply AEM author roles
- import_playbook: include-setup-aem-cms.yml
  vars:
    host_pattern: "tag_conga_variants_aem-author"
  tags:
    - aem-author
    - aem-cms

# Apply AEM publish roles
- import_playbook: include-setup-aem-cms.yml
  vars:
    host_pattern: "tag_conga_variants_aem-publish"
  tags:
    - aem-publish
    - aem-cms

# Apply aem-author dispatcher roles
- import_playbook: include-setup-aem-dispatcher.yml
  vars:
    host_pattern: "tag_conga_variants_aem-author"
  tags:
    - aem-dispatcher
    - aem-dispatcher-author

# Apply aem-publish dispatcher roles
- import_playbook: include-setup-aem-dispatcher.yml
  vars:
    host_pattern: "tag_conga_variants_aem-publish"
  tags:
    - aem-dispatcher
    - aem-dispatcher-publish

# flush author dispatcher(s)
- import_playbook: include-aem-dispatcher-flush.yml
  vars:
    host_pattern: "tag_conga_variants_aem-author"
  tags:
    - aem-dispatcher-flush
    - aem-dispatcher-flush-author

# flush publish dispatcher(s)
- import_playbook: include-aem-dispatcher-flush.yml
  vars:
    host_pattern: "tag_conga_variants_aem-publish"
  tags:
    - aem-dispatcher-flush
    - aem-dispatcher-flush-publish

# run smoke tests for author dispatcher
- import_playbook: include-smoke-tests-aem-dispatcher.yml
  vars:
    host_pattern: "tag_conga_variants_aem-author"
  tags:
    - aem-dispatcher-smoke-test-author
    - aem-dispatcher-smoke-test
    - smoke-test

# run smoke tests for publish dispatcher
- import_playbook: include-smoke-tests-aem-dispatcher.yml
  vars:
    host_pattern: "tag_conga_variants_aem-publish"
  tags:
    - aem-dispatcher-smoke-test-publish
    - aem-dispatcher-smoke-test
    - smoke-test

# run smoke tests on aem-author
- import_playbook: include-smoke-tests-aem-cms.yml
  vars:
    host_pattern: "tag_conga_variants_aem-author"
  tags:
    - aem-cms-smoke-test-author
    - aem-cms-smoke-test
    - smoke-test

# run smoke tests on aem-publish
- import_playbook: include-smoke-tests-aem-cms.yml
  vars:
    host_pattern: "tag_conga_variants_aem-publish"
  tags:
    - aem-cms-smoke-test-publish
    - aem-cms-smoke-test
    - smoke-test
