# Username for maven repository
vault_maven_repository_username: #if($mavenRepositoryUser!='__not_set__')${mavenRepositoryUser}#end

# Password for maven repository
vault_maven_repository_password: #if($mavenRepositoryPassword!='__not_set__')${mavenRepositoryPassword}#end


# Password for AEM "admin" user and felix console
vault_aem_admin_password: ${aemAdminPassword}
